apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
  namespace: personal
 spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 800Gi
  volumeName: pvc-e0119ee2-7db0-4bd6-9ecc-99f74d375db6