apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
  namespace: personal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 800Gi