// ==============================================================================
// Talos Client Configuration Output
// ==============================================================================

output "talosconfig" {
  value     = data.talos_client_configuration.talosconfig.talos_config
  sensitive = true
}
output "talosconfig_command" {
  value = "terraform output -raw talosconfig > ~/.talos/config"
}


// ==============================================================================
// Kubernetes Kubeconfig Output
// ==============================================================================

# output "kubeconfig" {
#   value     = talos_cluster_kubeconfig.kubeconfig.kubeconfig_raw
#   sensitive = true
# }

# output "kubeconfig_command" {
#   value = "terraform output -raw kubeconfig > ~/.kube/config"
# }

// ==============================================================================
// LAN-Accessible Kubeconfig Generation
// ==============================================================================

locals {
  // Decode the original kubeconfig generated by the Talos provider
  kubeconfig_decoded = yamldecode(talos_cluster_kubeconfig.kubeconfig.kubeconfig_raw)
}

resource "local_file" "kubeconfig_lan" {
  // The filename for the new kubeconfig
  filename = "${path.module}/kubeconfig.lan"

  // Use yamlencode to build the new YAML structure
  content = yamlencode({
    apiVersion      = local.kubeconfig_decoded.apiVersion
    kind            = local.kubeconfig_decoded.kind
    "current-context" = local.kubeconfig_decoded["current-context"]
    preferences     = local.kubeconfig_decoded.preferences

    // Re-build the clusters list with our modifications
    clusters = [
      {
        name = local.kubeconfig_decoded.clusters[0].name
        cluster = {
          // Point to the Proxmox host IP instead of the private VIP
          server = "https://${var.proxmox_host_lan_ip}:6443"
          // Skip TLS verify instead of using the CA
          insecure-skip-tls-verify = true
        }
      }
    ]

    // Keep the original contexts and users, which contain auth credentials
    contexts = local.kubeconfig_decoded.contexts
    users    = local.kubeconfig_decoded.users
  })
}

output "lan_kubeconfig_install_command" {
  value       = "cat kubeconfig.lan > ~/.kube/config"
  description = "Command to overwrite your default kubeconfig with the LAN-accessible version."
}
