apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-postgres
  namespace: personal
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3
  instances: 1
  enableSuperuserAccess: true
  
  managed:
    roles:
      - name: vaultwarden
        ensure: present
        login: true
        superuser: false
        passwordSecret:
          name: vaultwarden-postgres-user
        connectionLimit: -1
        inherit: true
        
  bootstrap:
    initdb:
      database: vaultwarden
      owner: vaultwarden
      secret:
        name: vaultwarden-postgres-user

  storage:
    size: 4Gi
    storageClass: longhorn