apiVersion: v1
kind: Namespace
metadata:
  name: otel-demo
  labels:
#    istio-injection: enabled
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-demo
  labels:
    helm.sh/chart: opentelemetry-demo-0.37.1

    app.kubernetes.io/instance: otel-demo
    app.kubernetes.io/version: "2.0.2"
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/managed-by: Helm