apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-media
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteOnce
  storageClassName: media
  local:
    path: /var/mnt/media
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - <worker-node-hostname>