apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-secure
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteOnce
  storageClassName: secure
  local:
    path: /var/mnt/secure
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - talos-worker-01