apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-photos
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Ti
  storageClassName: photos
