apiVersion: v1
kind: Service
metadata:
  name: sftp-server
  namespace: media
  labels:
    app: sftp-server
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.100.81
  selector:
    app: sftp-server
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
