apiVersion: v1
kind: Service
metadata:
  name: sftp-server
  namespace: media
  labels:
    app: sftp-server
spec:
  type: NodePort
  selector:
    app: sftp-server
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30022
