apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tracktor-data
  namespace: personal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
